name: ImageBuilder
# Run this workflow every time a new commit pushed to your repository
on: push
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.0.1
        with:
          url: https://hcpvaultworkshop-vault.vault.90c8be71-8b86-4967-b3d0-913bf19b96a0.aws.hashicorp.cloud:8200
          tlsSkipVerify: true
          namespace: admin
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/ci_app_secret api_key
      - name: Build Docker Image
        run: docker build . --file Dockerfile --build-arg app_secret="${{ env.APP_SECRET }}" -t vault-action-exampleapp
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.0.1
        with:
          url: https://hcpvaultworkshop-vault.vault.90c8be71-8b86-4967-b3d0-913bf19b96a0.aws.hashicorp.cloud:8200
          tlsSkipVerify: true
          token: ${{ secrets.VAULT_TOKEN }}
          namespace: admin
          secrets: |
            secret/data/ci app_secret
